In [2]:
import torch

# TENSOR

In [3]:
a = torch.tensor([1,2,3,4,5])
b = torch.tensor([1,2,3,4,5])
print(a*2)

tensor([ 2,  4,  6,  8, 10])


In [4]:
c = torch.tensor([[[1,2,3], [1,2,3,], 
                   [1,2,3,], [1,2,3]]])
c

tensor([[[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]]])

In [5]:
x = torch.tensor([1,2,3,4,5])
print(x[0])

tensor(1)


In [6]:
x[-1]

tensor(5)

In [7]:
matrix = torch.tensor([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [8]:
matrix[1:3, 1:3]

tensor([[5, 6],
        [8, 9]])

In [ ]:
embedding_matrix = torch.tensor([
    [0.1, 0.2, 0.3],
    [1.1, 1.2, 1.3],
    [2.1, 2.2, 2.3],
    [3.1, 3.2, 3.3],
    [4.1, 4.2, 4.3]
])

token_ids = torch.tensor([2,4,1])
output = embedding_matrix[token_ids]

print("Embedding Matrix: ")
print(embedding_matrix)

print("output: ")
print(output)

print("output Shape: ")
print(output.shape)

Embedding Matrix: 
tensor([[0.1000, 0.2000, 0.3000],
        [1.1000, 1.2000, 1.3000],
        [2.1000, 2.2000, 2.3000],
        [3.1000, 3.2000, 3.3000],
        [4.1000, 4.2000, 4.3000]])
output: 
tensor([[2.1000, 2.2000, 2.3000],
        [4.1000, 4.2000, 4.3000],
        [1.1000, 1.2000, 1.3000]])
output Shape: 
torch.Size([3, 3])


In [13]:
matrix = torch.randn(5,3)
print(matrix)

tensor([[-1.0244,  0.0864, -1.2512],
        [ 0.0544, -0.3402,  0.4958],
        [-0.1017, -0.6852, -1.0041],
        [ 0.9193,  0.2427, -0.9369],
        [ 1.7021,  0.2481, -0.5698]])
