In [2]:
import torch
import math
import torch.nn as nn

In [3]:
class Embedding(nn.Module):
    def __init__(self, vocab_size, embedding_dim):
        super().__init__()

        self.embedding_matrix = nn.Parameter(
            torch.randn(vocab_size, embedding_dim)
        )

    def forward(self, token_ids):
        return self.embedding_matrix[token_ids]

In [4]:
embedding = Embedding(
    vocab_size=50000,
    embedding_dim=512
)

token_ids = torch.tensor([[2,4,1], [1,2,3]])
output = embedding(token_ids)

print('Input Token IDs: ')
print(token_ids)

print("Output Embeddings: ")
print(output)

print("Output Shape:")
print(output.shape)

Input Token IDs: 
tensor([[2, 4, 1],
        [1, 2, 3]])
Output Embeddings: 
tensor([[[-0.8604,  0.6819, -0.4759,  ..., -2.1464,  0.0058, -0.0719],
         [ 1.8193, -0.1148, -0.7052,  ..., -0.9543, -0.5917,  0.7491],
         [-0.4135,  0.9888,  0.3079,  ..., -0.5980,  0.8223,  0.6838]],

        [[-0.4135,  0.9888,  0.3079,  ..., -0.5980,  0.8223,  0.6838],
         [-0.8604,  0.6819, -0.4759,  ..., -2.1464,  0.0058, -0.0719],
         [ 1.7316,  0.0927,  0.6926,  ..., -0.2893,  0.9261,  0.3528]]],
       grad_fn=<IndexBackward0>)
Output Shape:
torch.Size([2, 3, 512])


In [5]:
class PositionalEncoding(nn.Module):
    def __init__(self, d_model, max_seq_length):
        super().__init__()

        pe = torch.zeros(max_seq_length, d_model)

        position = torch.arange(max_seq_length).unsqueeze(1).float()

        div_term = torch.exp(
            torch.arange(0, d_model, 2).float()* (-math.log(10000.0)/d_model)
        )

        pe[:, 1::2] = torch.sin(position*div_term)
        pe[:, 1::2] = torch.cos(position*div_term)

        pe = pe.unsqueeze(0)

        self.register_buffer("pe", pe)

    def forward(self, x):
        seq_lenght = x.size(1)
        return x + self.pe[:, :seq_lenght]

In [6]:
d_model = 8
max_seq_length = 10

pe = PositionalEncoding(
    d_model=d_model,
    max_seq_length=max_seq_length
)

print(pe.pe.shape)

torch.Size([1, 10, 8])


In [7]:
batch_size = 2
seq_length = 5
d_model = 8

embeddings = torch.randn(batch_size, seq_length, d_model)

output = pe(embeddings)

print("Input Shape :", embeddings.shape)
print("Output Shape:", output.shape)

Input Shape : torch.Size([2, 5, 8])
Output Shape: torch.Size([2, 5, 8])


In [8]:
div_term = torch.exp(
    torch.arange(0, 8, 2).float()
    * (-math.log(10000.0) / d_model)
)

print(div_term)

tensor([1.0000e+00, 1.0000e-01, 1.0000e-02, 1.0000e-03])
